#!/bin/bash

scor='\033[0m'
cor1='\033[1;37m'
cor2='\033[1;31m'
cor3='\033[1;32m'
cor4='\033[1;36m'
cor5='\033[1;34m'
cor6='\033[1;35m'
cortxt='\033[1;33m'
corbar1='\033[41;1;37m'
corbar2='\033[44;1;37m'

clear
[[ "$(whoami)" != "root" ]] && {
echo -e "${cortxt}[${cor2}Erro${cortxt}] ${cor1}- ${cortxt}você precisa executar como root${scor}"
rm $HOME/Plus > /dev/null 2>&1; exit 0
}
_lnk=$(echo 'z1:y#x.5s0ul&p4hs$s.0a72d*n-e!v89e032:3r'| sed -e 's/[^a-z.]//ig'| rev); _Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig'); _1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig')
cd $HOME
fun_bar () {
comando[0]="$1"
comando[1]="$2"
(
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
) > /dev/null 2>&1 &
tput civis
echo -ne "  ${cortxt}AGUARDE ${cor1}- ${cortxt}["
while true; do
for((i=0; i<18; i++)); do
echo -ne "${cor2}#"
sleep 0.1s
done
[[ -e $HOME/fim ]] && rm $HOME/fim && break
echo -e "${cortxt}]"
sleep 1s
tput cuu1
tput dl1
echo -ne "  ${cortxt}AGUARDE ${cor1}- ${cortxt}["
done
echo -e "${cortxt}]${cor1} -${cor3} OK !${cor1}"
tput cnorm
}
function verif_key () {
krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Ink/list > /dev/null 2>&1
[[ ! -e "$_Ink/list" ]] && {
echo -e "\n${cor2}LINK INVALIDO!${scor}"
rm -rf $HOME/Plus > /dev/null 2>&1
sleep 2
clear; exit 1
}
}
echo -e "${cor5}════════════════════════════════════════════════${scor}"
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%40s%s%-12s\n' "SEJA MUITO BEM VINDO (A)" ; tput sgr0
echo -e "${cor5}════════════════════════════════════════════════${scor}"
echo ""
echo -e "                  ${cor2} ⚠️ ATENÇÃO ⚠️${scor}"
echo -e "                 ${cortxt}ESSE SCRIPT IRÁ !${scor}"
echo ""
echo -e "${cor2}• ${cortxt}INSTALAR UM CONJUNTO DE SCRIPTS COMO FERRAMENTAS!${scor}"
echo -e "${cor2}• ${cortxt}PARA O GERENCIAMENTO DE REDE, SISTEMA E USUÁRIOS!${scor}"
echo -e "${cor2}• ${cortxt}ISSO PODE DEMORAR ALGUNS MINUTOS!${scor}"
echo -e "${cor2}• ${cortxt}ATENÇAO É NECESSÁRIO QUE A VPS ESTEJA FORMATADA!${scor}"
echo ""
echo -e "${cor3}• ${cor3}DICA! ${cortxt}ULTILIZE O TEMA DARK EM SEU TERMINAL PARA${scor}"
echo -e "${cortxt}  UMA MELHOR EXPERIÊNCIA E VISUALIZACAO DO MESMO!${scor}"
echo ""
#-----------------------------------------------------------------------------------------------------------------

sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config  > /dev/null 2>&1
service ssh restart  > /dev/null 2>&1
echo -e "\n${cor4}VERIFICANDO LINK... ${cor1} $_key_${scor}" ; rm $_Ink/list > /dev/null 2>&1; wget -P $_Ink https://juniorfdtech.github.io/ntwrldssh/tools/list > /dev/null 2>&1; verif_key
sleep 3s
echo "/bin/menu" > /bin/h && chmod +x /bin/h > /dev/null 2>&1
#-----------------------------------------------------------------------------------------------------------------
echo -e "\n${cor3}LINK VALIDO!${cor3}"
sleep 1s
echo ""
[[ -f "$HOME/usuarios.db" ]] && {
clear
echo -e "${cor5}════════════════════════════════════════════════${scor}"
echo ""
echo -e "                 ${cortxt}• ${cor2}ATENCAO ${cortxt}• ${scor}"
echo ""
echo -e "${cortxt}Uma base de Dados de Usuários ${cor3}(usuarios.db) ${cortxt}Foi"
echo -e "Encontrada! Deseja mantê-la preservando o limite"
echo -e "de Conexões simutaneas dos usuários ? Ou Deseja"
echo -e "criar uma nova base de dados ?${scor}"
echo -e "\n${cor1}[${cor2}1${cor1}] ${cortxt}Manter Base de Dados Atual${scor}"
echo -e "${cor1}[${cor2}2${cor1}] ${cortxt}Criar uma Nova Base de Dados${scor}"
echo -e "${cor5}════════════════════════════════════════════════${scor}"
echo ""
tput setaf 2 ; tput bold ; read -p "Opção ?: " -e -i 1 optiondb ; tput sgr0
} || {
awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
}
[[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
clear
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-18s\n' " AGUARDE A INSTALAÇÃO" ; tput sgr0
echo ""
echo ""
echo -e "          ${cortxt}[${cor2}!${cortxt}] ${cor3}ATUALIZANDO SISTEMA ${cortxt}[${cor2}!${cortxt}]${scor}"
echo ""
echo -e "    ${cortxt}ATUALIZAÇÕES COSTUMA DEMORAR UM POUCO!${scor}"
echo ""
fun_attlist () {
apt-get update -y
[[ ! -d /usr/share/.plus ]] && mkdir /usr/share/.plus
echo "crz: $(date)" > /usr/share/.plus/.plus
}
fun_bar 'fun_attlist'
clear
echo ""
echo -e "          ${cortxt}[${cor2}!${cortxt}] ${cor3}INSTALANDO PACOTES ${cortxt}[${cor2}!${cortxt}] ${scor}"
echo ""
echo -e "${cortxt}ALGUNS PACOTES SAO EXTREMAMENTE  NECESSÁRIOS !${scor}"
echo ""
inst_pct () {
_pacotes=("bc" "man" "screen" "nano" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "htop" "jq" "curl" "figlet" "python2" "python3" "python-pip" "python3-pip")
for _prog in ${_pacotes[@]}; do
apt install $_prog -y
done
pip install speedtest-cli
}
fun_bar 'inst_pct'
[[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp ; ufw allow 80/tcp ; ufw allow 3128/tcp ; ufw allow 8799/tcp ; ufw allow 8080/tcp
clear
echo ""
echo -e "              ${cortxt}[${cor2}!${cortxt}] ${cor3}FINALIZANDO ${cortxt}[${cor2}!${cortxt}] ${scor}"
echo ""
echo -e "      ${cortxt}CONCLUINDO FUNÇÕES E DEFINIÇÕES! ${scor}"
echo ""
fun_bar "$_Ink/list $_lnk $_Ink $_1nk $key"
clear
echo ""
cd $HOME
echo -e "${cor4}
     ╔╗╔╔═╗╔╦╗  ╦ ╦╔═╗╦═╗╦  ╔╦╗  ╔═╗╔═╗╦ ╦
     ║║║║╣  ║   ║║║║ ║╠╦╝║   ║║  ╚═╗╚═╗╠═╣
     ╝╚╝╚═╝ ╩   ╚╩╝╚═╝╩╚═╩═╝═╩╝  ╚═╝╚═╝╩ ╩ MANAGEMENT"
echo ""
echo -e "        ${cortxt} • ${cor3}INSTALACAO CONCLUIDA${cortxt} • ${scor}"
echo ""
echo -e "${cor2} ${cortxt}COMANDO PRINCIPAL: ${cor3}menu${scor}"
rm $HOME/Plus && cat /dev/null > ~/.bash_history && history -c
