#!/bin/bash

scor='\033[0m'
cor1='\033[1;37m'
cor2='\033[1;31m'
cor3='\033[1;32m'
cor4='\033[1;36m'
cor5='${cor5}'
cor6='\033[1;35m'
cortxt='\033[1;33m'
corbar1='\033[41;1;37m'
corbar2='\033[44;1;37m'

clear
chk=$(cat /etc/ssh/sshd_config | grep Banner)
[[ $(netstat -nltp|grep 'dropbear' | wc -l) != '0' ]] && {
    local="/etc/bannerssh"
	[[ $(grep -wc $local /etc/default/dropbear) = '0' ]] && echo 'DROPBEAR_BANNER="/etc/bannerssh"' >>  /etc/default/dropbear
}
[[ "$(echo "$chk" | grep -v '#Banner' | grep Banner)" != "" ]] && {
	local=$(echo "$chk" |grep -v "#Banner" | grep Banner | awk '{print $2}')
} || {
    local="/etc/bannerssh"
    [[ $(grep -wc $local /etc/ssh/sshd_config) = '0' ]] && echo "Banner /etc/bannerssh" >> /etc/ssh/sshd_config
}
echo -e "${corbar2}             BANNER             ${scor}"
echo ""
echo -e "${cor2}[${cor4}1${cor2}]${cor1} • ${cortxt}ADICIONAR BANNER"
echo -e "${cor2}[${cor4}2${cor2}]${cor1} • ${cortxt}REMOVER BANNER"
echo -e "${cor2}[${cor4}3${cor2}]${cor1} • ${cortxt}VOLTAR"
echo ""
echo -ne "${cor3}OQUE DESEJA FAZER${cor2} ?${cor1} : "; read resp
if [[ "$resp" = "1" ]]; then
echo ""
echo -ne "${cor3}QUAL MENSAGEM DESEJA EXIBIR${cor2} ?${cor1} : "; read msg1
if [[ -z "$msg1" ]]; then
	echo -e "\n${cor2}Campo vazio ou invalido !${scor}"
	sleep 2
	banner
fi
echo -e "\n${cor2}[${cor4}01${cor2}]${cortxt} FONTE PEQUENA"
echo -e "${cor2}[${cor4}02${cor2}]${cortxt} FONTE MEDIA"
echo -e "${cor2}[${cor4}03${cor2}]${cortxt} FONTE GRANDE"
echo -e "${cor2}[${cor4}04${cor2}]${cortxt} FONTE GIGANTE"
echo ""
echo -ne "${cor3}QUAL O TAMANHO DA FONTE${cor2} ?${cor1} : "; read opc
if [[ "$opc" = "1" ]] || [[ "$opc" = "01" ]]; then
_size='6'
elif [[ "$opc" = "2" ]] || [[ "$opc" = "02" ]]; then
_size='4'
elif [[ "$opc" = "3" ]] || [[ "$opc" = "03" ]]; then
_size='3'
elif [[ "$opc" = "4" ]] || [[ "$opc" = "04" ]]; then
_size='1'
fi

echo -e "\n${cor2}[${cor4}01${cor2}]${cortxt} AZUL"
echo -e "${cor2}[${cor4}02${cor2}]${cortxt} VERDE"
echo -e "${cor2}[${cor4}03${cor2}]${cortxt} VERMELHO"
echo -e "${cor2}[${cor4}04${cor2}]${cortxt} AMARELO"
echo -e "${cor2}[${cor4}05${cor2}]${cortxt} ROSA"
echo -e "${cor2}[${cor4}06${cor2}]${cortxt} CYANO"
echo -e "${cor2}[${cor4}07${cor2}]${cortxt} LARANJA"
echo -e "${cor2}[${cor4}08${cor2}]${cortxt} ROXO"
echo -e "${cor2}[${cor4}09${cor2}]${cortxt} PRETO"
echo -e "${cor2}[${cor4}10${cor2}]${cortxt} SEM COR"
echo ""
echo -ne "${cor3}QUAL A COR${cor2} ?${cor1} : "; read ban_cor
if [[ "$ban_cor" = "1" ]] || [[ "$ban_cor" = "01" ]]; then
echo "<h$_size><font color='blue'>$msg1" >> $local
elif [[ "$ban_cor" = "2" ]] || [[ "$ban_cor" = "02" ]]; then
echo "<h$_size><font color='green'>$msg1" >> $local
elif [[ "$ban_cor" = "3" ]] || [[ "$ban_cor" = "03" ]]; then
echo "<h$_size><font color='red'>$msg1" >> $local
elif [[ "$ban_cor" = "4" ]] || [[ "$ban_cor" = "04" ]]; then
echo "<h$_size><font color='yellow'>$msg1" >> $local
elif [[ "$ban_cor" = "5" ]] || [[ "$ban_cor" = "05" ]]; then
echo "<h$_size><font color='#F535AA'>$msg1" >> $local
elif [[ "$ban_cor" = "6" ]] || [[ "$ban_cor" = "06" ]]; then
echo "<h$_size><font color='cyan'>$msg1" >> $local
elif [[ "$ban_cor" = "7" ]] || [[ "$ban_cor" = "07" ]]; then
echo "<h$_size><font color='#FF7F00'>$msg1" >> $local
elif [[ "$ban_cor" = "8" ]] || [[ "$ban_cor" = "08" ]]; then
echo "<h$_size><font color='#9932CD'>$msg1" >> $local
elif [[ "$ban_cor" = "9" ]] || [[ "$ban_cor" = "09" ]]; then
echo "<h$_size><font color='black'>$msg1" >> $local
elif [[ "$ban_cor" = "10" ]]; then
echo "<h$_size>$msg1</h$_size>" >> $local
/etc/init.d/ssh restart > /dev/null 2>&1
echo -e "\n${cor3}BANNER DEFINIDO !${scor}"
sleep 2
menu
else
echo -e "\n${cor2}Opcao invalida !${scor}"
	sleep 2
	banner
fi
echo "</font></h$_size>" >> $local
service ssh restart > /dev/null 2>&1 && service dropbear restart > /dev/null 2>&1
echo -e "\n${cor3}BANNER DEFINIDO !${scor}"
unset ban_cor
elif [[ "$resp" = "2" ]]; then
	echo " " > $local
	echo -e "\n${cor3}BANNER EXCLUIDO !${scor}"
	service ssh restart > /dev/null 2>&1 && service dropbear restart > /dev/null 2>&1
	sleep 2
	menu
elif [[ "$resp" = "3" ]]; then
	menu
else
	echo -e "\n${cor2}Opcao invalida !${scor}"
	sleep 2
	banner
fi