#!/bin/bash

scor='\033[0m'
cor1='\033[1;37m'
cor2='\033[1;31m'
cor3='\033[1;32m'
cor4='\033[1;36m'
cor5='${cor5}'
cor6='\033[1;35m'
cortxt='\033[1;33m'
corbar1='\033[41;1;37m'
corbar2='\033[44;1;37m'

#
menu(){
FILE=sites.cake
if [ -f "$FILE" ]; then
clear
else
touch sites.cake
fi

clear
echo -e "${corbar2}            BLOQUEADOR WEBSITE              ${scor}"
echo""
echo -e "${cor2}• ${cortxt}VBLOQUEIO PARA TUNELAMENTO SSH (VPN)!${scor}"
echo ""
echo -e "${cor5}============================================================"
echo -e "${cortxt} USE AS STRING COMO ${cor1}(www.google.com) ${cortxt}PARA BLOQUEAR!"
echo -e "${cor5}============================================================"
tput setaf 7 ; tput bold ; printf '%s' "[1]◉>"; tput setaf 3 ; printf '%s' " BLOQUEAR SITE."  ; echo ""
tput setaf 7 ; tput bold ; printf '%s' "[2]◉>"; tput setaf 3 ; printf '%s' " DESBLOQUEAR SITE." ;  echo ""
tput setaf 7 ; tput bold ; printf '%s' "[3]◉>"; tput setaf 3 ; printf '%s' " DESBLOQUEAR TODOS OS SITES." ;  echo ""
tput setaf 7 ; tput bold ; printf '%s' "[4]◉>"; tput setaf 3 ; printf '%s' " VISUALIZAR LISTA BLOQUEADA." ;  echo ""
tput setaf 7 ; tput bold ; printf '%s' "[0]◉>"; tput setaf 3 ; printf '%s' " VOLTAR AO MENU ANTERIOR." ;  echo ""
echo -e "${cor5}============================================================"
echo -ne "${cor1}[ESCOLHA UM NUMERO]${cor1}: "; read opcao
case $opcao in
	01|1) block ;;
	02|2) unblock ;;
	03|3) unblockall ;;
	04|4) view ;;
        00|0) bash menu ;;
        *)
menu
esac
}
menu
block(){
clear
tput setaf 2 ; tput bold ; printf '%s' "|*|"; tput setaf 7 ; printf '%s' " { BLOQUEAR SITE } " ; tput setaf 2 ; tput bold ; printf '%s' "|*|"; echo ""
echo -e "${cor5}============================================================"
tput setaf 7 ; tput bold ; printf '%s' "[1]•>"; tput setaf 3 ; printf '%s' " BLOQUEAR SITE."  ; echo ""
tput setaf 7 ; tput bold ; printf '%s' "[2]•>"; tput setaf 3 ; printf '%s' " VOLTAR AO MENU."  ; echo ""
echo -e "${cor5}============================================================"
echo -ne "${cor1}[ESCOLHA UM NUMERO]${cor1}: "; read option
if [ "$option" = "1" ]; then 
clear
echo ""
tput setaf 2 ; tput bold ; printf '%s' "|*|"; tput setaf 7 ; printf '%s' " { DIGITE O SITE } " ; tput setaf 2 ; tput bold ; printf '%s' "|*|"; echo ""
echo ""
echo -e "${cor1}INSIRA O SITE:"
echo ""
read website
if [ -z $website ]; then
clear
echo ""
echo -e "${cor2}OPS! ESTA VAZIO. DIGITE UM SITE REAL, ${cor1}EX; (www.google.com)"
echo ""
sleep 5s
block
else
clear
cat sites.cake | grep $website && site=1 || site=0
clear
if [ "$site" = "1" ]; then
clear
echo ""
echo ""
tput setaf 2 ; tput bold ; printf '%s' "|*|"; tput setaf 7 ; printf '%s' " { DIGITE O SITE } " ; tput setaf 2 ; tput bold ; printf '%s' "|*|"; echo ""
echo ""
tput setaf 2 ; tput bold ; printf '%s' "|*|"; tput setaf 3 ; printf '%s' "O SITE ( $website ) JA ESTA BLOQUEADO!" ; tput setaf 2 ; tput bold ; printf '%s' "|*|"; echo ""
sleep 5s
block
elif [ "$site" = "0" ]; then
iptables -A INPUT -s $website -j DROP && iptables -A FORWARD -s $website  -j DROP
echo "$website" >> sites.cake
clear
echo ""
echo ""
tput setaf 2 ; tput bold ; printf '%s' "|*|"; tput setaf 2 ; printf '%s' "SITE BLOQUEADO!: $website" ; tput setaf 2 ; tput bold ; printf '%s' "|*|"; echo ""
sleep 5s
block
else
clear
echo "VIOLADO!"
sleep 5s
block
fi
fi
elif [ "$option" = "2" ]; then
menu
else
clear
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%30s%s%-10s\n' "DIGITE APENAS 1 OU 2" ; tput sgr0 ; echo ""
sleep 5s
block
fi
}

unblock(){
clear
tput setaf 2 ; tput bold ; printf '%s' "|*|"; tput setaf 7 ; printf '%s' " { DESBLOQUEAR SITE } " ; tput setaf 2 ; tput bold ; printf '%s' "|*|"; echo ""
echo -e "${cor5}============================================================"
tput setaf 7 ; tput bold ; printf '%s' "[1]◉>"; tput setaf 3 ; printf '%s' " DESBLOQUEAR SITE."  ; echo ""
tput setaf 7 ; tput bold ; printf '%s' "[2]◉>"; tput setaf 3 ; printf '%s' " VOLTAR AO MENU."  ; echo ""
echo -e "${cor5}============================================================"
echo -ne "${cor1}[ESCOLHA UM NUMERO]${cor1}: "; read option
if [ "$option" = "1" ]; then
clear
echo ""
tput setaf 2 ; tput bold ; printf '%s' "|*|"; tput setaf 7 ; printf '%s' " { DIGITE O SITE } " ; tput setaf 2 ; tput bold ; printf '%s' "|*|"; echo ""
echo ""
echo -e "${cor1}INSIRA O SITE:"
echo ""
read website
if [ -z $website ]; then
clear
echo ""
echo -e "${cor2}OPS! ESTA VAZIO. DIGITE UM SITE REAL, ${cor1}EX; (www.google.com)"
echo ""
sleep 5s
unblock
else
clear
cat sites.cake | grep $website && site=1 || site=0
clear
if [ "$site" = "0" ]; then
clear
echo ""
echo ""
tput setaf 2 ; tput bold ; printf '%s' "|*|"; tput setaf 3 ; printf '%s' "O SITE ( $website ) JA ESTA DESBLOQUEADO!" ; tput setaf 2 ; tput bold ; printf '%s' "|*|"; echo ""
sleep 5s
unblock
elif [ "$site" = "1" ]; then
iptables -D INPUT -s $website -j DROP && iptables -D FORWARD -s $website  -j DROP
grep -v "$website" sites.cake > temp && mv temp sites.cake
clear
echo ""
echo ""
tput setaf 2 ; tput bold ; printf '%s' "|*|"; tput setaf 2 ; printf '%s' "SITE DESBLOQUEADO!: $website" ; tput setaf 2 ; tput bold ; printf '%s' "|*|"; echo ""
sleep 5s
unblock
else
clear
echo "VIOLADO!"
sleep 5s
unblock
fi
fi
elif [ "$option" = "2" ]; then
menu
else
clear
tput setaf 2 ; tput bold ; printf '%s' "|*|"; tput setaf 7 ; printf '%s' " { APENAS 1 OU 2 ! } " ; tput setaf 2 ; tput bold ; printf '%s' "|*|"; echo ""
sleep 5s
unblock
fi
}

view()
{
clear
echo ""
tput setaf 2 ; tput bold ; printf '%s' "|*|"; tput setaf 7 ; printf '%s' " { SITE BLOQUEADOS } " ; tput setaf 2 ; tput bold ; printf '%s' "|*|"; echo ""
echo -e "${cor5}============================================================"
printf "${cortxt}"
cat sites.cake
printf "${cor1}"
echo -e "${cor5}============================================================"
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%30s%s%-10s\n' "ENTER PARA VOLTAR AO MENU!" ; tput sgr0 ; echo ""
read cake
menu
}
unblockall()
{
FILE=sites.cake
if [ -f "$FILE" ]; then
clear
else
touch sites.cake
fi
clear
tput setaf 2 ; tput bold ; printf '%s' "|*|"; tput setaf 7 ; printf '%s' " { DESBLOQUEAR } " ; tput setaf 2 ; tput bold ; printf '%s' "|*|"; echo ""
echo -e "${cor5}============================================================"
tput setaf 7 ; tput bold ; printf '%s' "[1]◉>"; tput setaf 3 ; printf '%s' " DESBLOQUEAR TODOS OS SITE."  ; echo ""
tput setaf 7 ; tput bold ; printf '%s' "[2]◉>"; tput setaf 3 ; printf '%s' " VOLTAR AO MENU."  ; echo ""
echo -e "${cor5}============================================================"
echo -ne "${cor1}[ESCOLHA UM NUMERO]${cor1}: "; read option
if [ "$option" = "1" ]; then 
clear
tput setaf 7 ; tput setab 1 ; tput bold ; printf '%30s%s%-10s\n' "ISSO IRA REMOVER TODAS AS REGRAS DE BLOQUEIO!" ; tput sgr0 ;
echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; printf '%30s%s%-10s\n' "DESEJAR REALMENTE CONTINUAR ?" ; tput sgr0 ;
echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; printf '%30s%s%-10s\n' "SIM/NAO" ; tput sgr0 ;
echo ""
echo -e "${cor1}DIGITE SUA RESPOSTA: "
echo ""
read option2
if [ "$option2" = "SIM" ]; then 
clear
iptables -F
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%30s%s%-10s\n' "FEITO !" ; tput sgr0 ; echo ""
rm -f sites.cake
sleep 5s
unblockall
elif [ "$option2" = "NAO" ]; then 
unblockall
else
clear
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%30s%s%-10s\n' "APENAS SIM OU NAO" ; tput sgr0 ; echo ""
tput setaf 2 ; tput bold ; printf '%s' "|*|"; tput setaf 7 ; printf '%s' " { APENAS SIM OU NAO ! } " ; tput setaf 2 ; tput bold ; printf '%s' "|*|"; echo ""
sleep 5s
unblockall
fi
elif [ "$option" = "2" ]; then 
menu
else
clear
tput setaf 2 ; tput bold ; printf '%s' "|*|"; tput setaf 7 ; printf '%s' " { APENAS 1 OU 2 ! } " ; tput setaf 2 ; tput bold ; printf '%s' "|*|"; echo ""
sleep 5s
unblockall
fi
}
menu
