#!/bin/bash

scor='\033[0m'
cor1='\033[1;37m'
cor2='\033[1;31m'
cor3='\033[1;32m'
cor4='\033[1;36m'
cor5='\033[1;34m'
cor6='\033[1;35m'
cortxt='\033[1;33m'
corbar1='\033[41;1;37m'
corbar2='\033[44;1;37m'

clear
fun_bar() {
    comando[0]="$1"
    comando[1]="$2"
    (
        [[ -e $HOME/fim ]] && rm $HOME/fim
        ${comando[0]} -y >/dev/null 2>&1
        ${comando[1]} -y >/dev/null 2>&1
        touch $HOME/fim
    ) >/dev/null 2>&1 &
    tput civis
    echo -ne "${cortxt}["
    while true; do
        for ((i = 0; i < 18; i++)); do
            echo -ne "${cor2}#"
            sleep 0.1s
        done
        [[ -e $HOME/fim ]] && rm $HOME/fim && break
        echo -e "${cortxt}]"
        sleep 1s
        tput cuu1
        tput dl1
        echo -ne "${cortxt}["
    done
    echo -e "${cortxt}]${cor1} -${cor3} OK !${cor1}"
    tput cnorm
}

fun_botOnOff() {
    [[ $(ps x | grep "bot_plus" | grep -v grep | wc -l) = '0' ]] && {
        clear
        echo -e "${corbar2}             INSTALADOR BOT NET WORLD SSH               ${scor}\n"
        echo -ne "${cor3}INFORME SEU TOKEN:${cor1} "
        read tokenbot
        echo ""
        echo -ne "${cor3}INFORME SEU ID:${cor1} "
        read iduser
        clear
        echo -e "${cor3}INICIANDO BOT NET WORLD SSH ${scor}\n"
        fun_bot1() {
            [[ ! -e "/etc/SSHPlus/ShellBot.sh" ]] && {
				wget -qO- https://www.dropbox.com/s/yg001kkyir94w17/ShellBot.sh >/etc/SSHPlus/ShellBot.sh
			}
            cd /etc/SSHPlus
            screen -dmS bot_plus ./bot $tokenbot $iduser >/dev/null 2>&1
            [[ $(grep -wc "bot_plus" /etc/autostart) = '0' ]] && {
                echo -e "ps x | grep 'bot_plus' | grep -v 'grep' || cd /etc/SSHPlus && screen -dmS bot_plus ./bot $tokenbot $iduser && cd $HOME" >>/etc/autostart
            } || {
                sed -i '/bot_plus/d' /etc/autostart
                echo -e "ps x | grep 'bot_plus' | grep -v 'grep' || cd /etc/SSHPlus && screen -dmS bot_plus ./bot $tokenbot $iduser && cd $HOME" >>/etc/autostart
            }
            [[ $(crontab -l | grep -c "verifbot") = '0' ]] && (
                crontab -l 2>/dev/null
                echo "@daily /bin/verifbot"
            ) | crontab -
            cd $HOME
        }
        fun_bar 'fun_bot1'
        [[ $(ps x | grep "bot_plus" | grep -v grep | wc -l) != '0' ]] && echo -e "\n${cor3} BOT NET WORLD SSH ATIVADO !${scor}" || echo -e "\n${cor2} ERRO! REANALISE SUAS INFORMACOES${scor}"
        sleep 2
        menu
    } || {
        clear
        echo -e "${cor3}PARANDO BOT NET WORLD SSH... ${scor}\n"
        fun_bot2() {
            screen -r -S "bot_plus" -X quit
            screen -wipe 1>/dev/null 2>/dev/null
            [[ $(grep -wc "bot_plus" /etc/autostart) != '0' ]] && {
                sed -i '/bot_plus/d' /etc/autostart
            }
            [[ $(crontab -l | grep -c "verifbot") != '0' ]] && crontab -l | grep -v 'verifbot' | crontab -
            sleep 1
        }
        fun_bar 'fun_bot2'
        echo -e "\n${cor3} ${cor2}BOT NET WORLD SSH PARADO! ${scor}"
        sleep 2
        menu
    }
}

fun_instbot() {
    echo -e "${corbar2}             INSTALADOR BOT NET WORLD SSH             ${scor}\n"
    echo -e "                 ${cortxt}[${cor2}!${cortxt}] ${cor2}ATENCAO ${cortxt}[${cor2}!${cortxt}]${scor}"
    echo -e "\n${cor3}1° ${cor1}- ${cortxt}PELO SEU TELEGRAM ACESSE OS SEGUINTES BOT${cor1}:${scor}"
    echo -e "\n${cor3}2° ${cor1}- ${cortxt}BOT ${cor1}@BotFather ${cortxt}CRIE O SEU BOT ${cor2}OPCAO: ${cor1}/newbot${scor}"
    echo -e "\n${cor3}3° ${cor1}- ${cortxt}BOT ${cor1}@userinfobot ${cortxt}E PEGUE SEU ID ${cor2}OPCAO: ${cor1}/id${scor}"
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${cor3}"
    echo ""
    read -p "DESEJA CONTINUAR ? [s/n]: " -e -i s resposta
    [[ "$resposta" = 's' ]] && {
        fun_botOnOff
    } || {
        echo -e "\n${cor2}Retornando...${scor}"
        sleep 2
        menu
    }
}
[[ -f "/etc/SSHPlus/ShellBot.sh" ]] && fun_botOnOff || fun_instbot
#fim
