#!/bin/bash

scor='\033[0m'
cor1='\033[1;37m'
cor2='\033[1;31m'
cor3='\033[1;32m'
cor4='\033[1;36m'
cor5='\033[1;34m'
cor6='\033[1;35m'
cortxt='\033[1;33m'
corbar1='\033[41;1;37m'
corbar2='\033[44;1;37m'

clear
if [ ! -e /usr/local/bin/reboot_sys ]; then
	echo "#!/bin/bash" > /usr/local/bin/reboot_sys 
	echo 'tanggal=$(date +"%d-%m-%Y")' >> /usr/local/bin/reboot_sys 
	echo 'waktu=$(date +"%T")' >> /usr/local/bin/reboot_sys 
	echo 'echo -e "${cor1}      Successfully Reboot On $tanggal Time $waktu." >> /root/reboot-log.txt' >> /usr/local/bin/reboot_sys 
	echo ""
	echo '/sbin/shutdown -r now' >> /usr/local/bin/reboot_sys 
	chmod +x /usr/local/bin/reboot_sys
fi

echo -e "${cor5}════════════════════════════════════════════════${scor}"
echo -e "${corbar2}                 AUTO REBOOT               ${scor}"
echo -e "${cor5}════════════════════════════════════════════════${scor}"
echo -e "${scor}                                                   "
echo -e "${cor2}[${cor4}1${cor2}] ${cor5}◉ ${cortxt}REINICIAR A CADA 1H ${cor2}"
echo -e "${cor2}[${cor4}2${cor2}] ${cor5}◉ ${cortxt}REINICIAR A CADA 2H ${cor2}" 
echo -e "${cor2}[${cor4}3${cor2}] ${cor5}◉ ${cortxt}REINICIAR A CADA 12H ${cor2}" 
echo -e "${cor2}[${cor4}4${cor2}] ${cor5}◉ ${cortxt}REINICIAR UMA VEZ POR DIA ${cor2}" 
echo -e "${cor2}[${cor4}5${cor2}] ${cor5}◉ ${cortxt}REINICIAR UMA VEZ POR SEMANA ${cor2}"
echo -e "${cor2}[${cor4}6${cor2}] ${cor5}◉ ${cortxt}REINICIAR MENSALMENTE ${cor2}"  
echo -e "${cor2}[${cor4}7${cor2}] ${cor5}◉ ${cortxt}LOGS DE REINICIALIZAÇÃO ${cor2}" 
echo -e "${cor2}[${cor4}8${cor2}] ${cor5}◉ ${cortxt}REMOVER REINICIALIZAÇÃO ${cor2}" 
echo -e "${cor2}[${cor4}x${cor2}] ${cor5}◉ ${cortxt}SAIR ${cor2}"
echo -e "${scor}                                                   "
read -p "SELECIONE A OPÇÃO DESEJADA [1-8 ou x] : " Reboot_Sys
echo -e "${scor}                                                   "
clear
case $Reboot_Sys in
		1)
		clear
		echo "10 * * * * root /usr/local/bin/reboot_sys" > /etc/cron.d/reboot_sys
		echo -e "${scor}                                                   "
		echo -e "${cor5}════════════════════════════════════════════════${scor}"
		echo -e "${scor}                                                   "
		echo -e "${cor1}                          Reiniciar a cada 1H   "
		echo -e "${scor}                                                   "
		echo -e "${cor5}════════════════════════════════════════════════${scor}"
		echo ""
        read -sp " Pressione ENTER para voltar"
        echo ""
        reboot_sys_auto
        ;;
		2)
		clear
		echo "10 */6 * * * root /usr/local/bin/reboot_sys" > /etc/cron.d/reboot_sys
		echo -e "${scor}                                                   "
		echo -e "${cor5}════════════════════════════════════════════════${scor}"
		echo -e "${scor}                                                   "
		echo -e "${cor1}                          Reiniciar a cada 2H   "
		echo -e "${scor}                                                   "
		echo -e "${cor5}════════════════════════════════════════════════${scor}"
		echo ""
        read -sp " Pressione ENTER para voltar"
        echo ""
        reboot_sys_auto
        ;;
		3)
		clear
		echo "10 */12 * * * root /usr/local/bin/reboot_sys" > /etc/cron.d/reboot_sys
		echo -e "${scor}                                                   "
		echo -e "${cor5}════════════════════════════════════════════════${scor}"
		echo -e "${scor}                                                   "
		echo -e "${cor1}                        Reiniciar a cada 12H    "
		echo -e "${scor}                                                   "
		echo -e "${cor5}════════════════════════════════════════════════${scor}"
		echo ""
        read -sp " Pressione ENTER para voltar"
        echo ""
        reboot_sys_auto
        ;;
		4)
		clear
		echo "10 0 * * * root /usr/local/bin/reboot_sys" > /etc/cron.d/reboot_sys
		echo -e "${scor}                                                   "
		echo -e "${cor5}════════════════════════════════════════════════${scor}"
		echo -e "${scor}                                                   "
		echo -e "${cor1}                     Reiniciar uma vez por dia  "
		echo -e "${scor}                                                   "
		echo -e "${cor5}════════════════════════════════════════════════${scor}"
		echo ""
        " Pressione ENTER para voltar"
        echo ""
        reboot_sys_auto
        ;;
		5)
		clear
		echo "10 0 */7 * * root /usr/local/bin/reboot_sys" > /etc/cron.d/reboot_sys
		echo -e "${scor}                                                   "
		echo -e "${cor5}════════════════════════════════════════════════${scor}"
		echo -e "${scor}                                                   "
		echo -e "${cor1}                   Reiniciar uma vez por semana "
		echo -e "${scor}                                                   "
		echo -e "${cor5}════════════════════════════════════════════════${scor}"
		echo ""
        read -sp " Pressione ENTER para voltar"
        echo ""
        reboot_sys_auto
        ;;
		6)
		clear
		echo "10 0 1 * * root /usr/local/bin/reboot_sys" > /etc/cron.d/reboot_sys
		echo -e "${scor}                                                   "
		echo -e "${cor5}════════════════════════════════════════════════${scor}"
		echo -e "${scor}                                                   "
		echo -e "${cor1}                      Reiniciar uma vez por mês "
		echo -e "${scor}                                                   "
		echo -e "${cor5}════════════════════════════════════════════════${scor}"
		echo ""
        read -sp " Pressione ENTER para voltar"
        echo ""
        reboot_sys_auto
        ;;
		7)
		clear
		if [ ! -e /root/reboot-log.txt ]; then
	         echo -e "${scor}                                                   "
		     echo -e "${cor5}════════════════════════════════════════════════${scor}"
		     echo -e "${scor}                                                   "
			 echo -e "${cor1}          Nenhuma atividade de reinicialização encontrada"
			 echo -e "${scor}                                                   "
		     echo -e "${cor5}════════════════════════════════════════════════${scor}"
			 echo -e "${scor}                                                   "
			 echo ""
             read -sp " Pressione ENTER para voltar"
             echo ""
             reboot_sys_auto
	         else 
	         echo -e "${scor}                                                   "
		     echo -e "${cor5}════════════════════════════════════════════════${scor}"
		     echo -e "${scor}                                                   "
			 echo -e "\e[${cor1}                          LOG REBOOT         "
			 echo -e "${scor}                                                   "
			 cat /root/reboot-log.txt
			 echo -e "${scor}                                                   "
		     echo -e "${cor5}════════════════════════════════════════════════${scor}"
			 echo -e "${scor}                                                   "
			 echo ""
             read -sp " Pressione ENTER para voltar"
             echo ""
             reboot_sys_auto
        fi
		exit
		;;
		8)
		clear
		rm -f /etc/cron.d/reboot_sys
		echo -e "${scor}                                                   "
		echo -e "${cor5}════════════════════════════════════════════════${scor}"
		echo -e "${scor}                                                   "
		echo -e "${cor1}                       Auto-Reboot Removido     "
		echo -e "${scor}                                                   "
		echo -e "${cor5}════════════════════════════════════════════════${scor}"
		echo ""
        read -sp "Pressione ENTER para voltar"
        echo ""
        reboot_sys_auto
        ;;
		x)
        echo -e "${cor2}Menu Principal...${scor}"
        sleep 1s
        menu
		;;
		*)
        reboot_sys_auto
		;;
		esac
		