#!/bin/bash

scor='\033[0m'
cor1='\033[1;37m'
cor2='\033[1;31m'
cor3='\033[1;32m'
cor4='\033[1;36m'
cor5='\033[1;34m'
cor6='\033[1;35m'
cortxt='\033[1;33m'
corbar1='\033[41;1;37m'
corbar2='\033[44;1;37m'

fun_swap() {
_diskText=$(df -h | awk '$NF=="/"{printf "%d/%dGB + (%s)\n", $3,$2,$5}')
_swap1=$(free -h | grep -i swap | awk {'print $2'})
_swap4=$(free | awk '/Swap/{printf("%.1f%"), $3/($2+.000000001)*100}';)
    clear
echo -e "${corbar2}                    GERENCIAR MEMORIA VIRTUAL                 ${scor}"
        echo ""
		echo -e "${cor2}• ${cortxt}Memoria Swap é uma memoria extra que é usada para a memoria Ram!${scor}"
		echo -e "${cor2}• ${cortxt}Atenção nunca use a memoria toda do espaço do disco use somente o suficiente${scor}"
		echo ""
echo -e "${cor1}══════════════════════════════════════════════════════════════${scor}"
        echo -e "${cor2}[${cor4}01${cor2}] ${cor1}◉ ${cortxt}ATIVAR SWAP / ALTERAR VALOR DO SWAP ${scor}"
		echo -e "${cor2}[${cor4}02${cor2}] ${cor1}◉ ${cortxt}DESATIVAR SWAP${scor}"
		echo -e "${cor2}[${cor4}00${cor2}] ${cor1}◉ ${cortxt}VOLTAR${scor}"
echo -e "${cor1}══════════════════════════════════════════════════════════════${scor}"
                echo -ne "${cor1}O QUE DESEJA FAZER?${cor1}: "; read resposta
		if [[ "$resposta" = '1' ]]; then
            clear
			echo -e "${corbar2}            MEMORIA VIRTUAL              ${scor}"
			echo ""
			echo -ne "${cortxt}QUANTOS GIGAS DESEJA ULTILIZAR ${cortxt}?${cor1}: "
			read gigas
            [[ -z "$gigas" ]] && {
					echo ""
					echo -e "${cor2}GIGAS INVALIDO!"
					sleep 2
					clear
					menu
				}
            echo ""
			echo -e "${cortxt}INICIANDO MEMORIA VIRTUAL: ${cor1}$gigas GB${cortxt}"
			echo ""
            swapoff -a
            rm -rf /bin/ram.img > /dev/null 2>&1
            fallocate -l ${gigas}G /bin/ram.img > /dev/null 2>&1
            chmod 600 /bin/ram.img > /dev/null 2>&1
            mkswap /bin/ram.img > /dev/null 2>&1
            swapon /bin/ram.img > /dev/null 2>&1
            echo 100 > /proc/sys/vm/swappiness
            echo '/bin/ram.img none swap sw 0 0' | sudo tee -a /etc/fstab > /dev/null 2>&1
            echo ""
			echo -e "${cor3}MEMORIA VIRTUAL ATIVADO !${cortxt}"
            sleep 4s
			fun_swap
        elif [[ "$resposta" = '2' ]]; then
            clear
			echo -e "${corbar2}            DESATIVANDO MEMORIA VIRTUAL              ${scor}"
            swapoff -a
            rm -rf /bin/ram.img > /dev/null 2>&1
            echo ""
			echo -e "${cor2}MEMORIA VIRTUAL DESATIVADO !${cortxt}"
			sleep 4s
			fun_swap
        elif [[ "$resposta" = '0' ]]; then
			echo ""
			menu
		else
			echo ""
			fun_swap
		fi 
}
fun_swap
