#!/bin/bash

scor='\033[0m'
cor1='\033[1;37m'
cor2='\033[1;31m'
cor3='\033[1;32m'
cor4='\033[1;36m'
cor5='\033[1;34m'
cor6='\033[1;35m'
cortxt='\033[1;33m'
corbar1='\033[41;1;37m'
corbar2='\033[44;1;37m'

[[ ! -d /etc/SSHPlus ]] && exit 0
[[ ! -d /etc/bot/revenda ]] && exit 0
for arq in $(ls /etc/bot/revenda); do
	_diasR=$(grep -w 'DIAS_REVENDA' /etc/bot/revenda/$arq/$arq | awk '{print $NF}')
	[[ "$_diasR" -eq '0' ]] && {
		[[ "$(grep -wc 'SUBREVENDA' /etc/bot/revenda/$arq/$arq)" != '0' ]] && {
			while read _listsub3; do
				_usub3="$(echo $_listsub3 | awk '{print $2}')"
				_dir_users="/etc/bot/revenda/$_usub3/usuarios"
				[[ "$(ls $_dir_users | wc -l)" != '0' ]] && {
					for _user in $(ls $_dir_users); do
						usermod -L $_user
						pkill -U $_user
					done
				}
				[[ $(grep -wc $_usub3 /etc/bot/lista_suspensos) == '0' ]] && {
					mv /etc/bot/revenda/$_usub3 /etc/bot/suspensos/$_usub3
					grep -w "$_usub3" /etc/bot/lista_ativos >>/etc/bot/lista_suspensos
				}
			done <<<"$(grep -w 'SUBREVENDA' /etc/bot/revenda/$arq/$arq)"
		}
		[[ "$(ls /etc/bot/revenda/$arq/usuarios | wc -l)" != '0' ]] && {
			for _user in $(ls /etc/bot/revenda/$arq/usuarios); do
				usermod -L $_user
				pkill -U $_user
			done
		}
		[[ $(grep -wc $arq /etc/bot/lista_suspensos) == '0' ]] && {
			mv /etc/bot/revenda/$arq /etc/bot/suspensos/$arq
			grep -w "$arq" /etc/bot/lista_ativos >>/etc/bot/lista_suspensos
		}
	} || {
		_days=$(($_diasR - 1))
		sed -i "/\b$arq\b/ s/DIAS: $_diasR/DIAS: $_days/" /etc/bot/lista_ativos
		sed -i "/DIAS_REVENDA/ s/$_diasR/$_days/" /etc/bot/revenda/$arq/$arq
		echo $arq $_diasR DIAS ALTERADO PARA $_days
	}
done
